listeners:
  abc3:
    bind: 0.0.0.0:4003
    targets: []
  google:
    bind: 0.0.0.0:1443
    targets:
    - aafawefwef:22
    - 192.168.44.113:2332
    - 192.168.33.42:80
    - www.google.com:443
  abc2:
    bind: 0.0.0.0:4004
    targets: []
  abc:
    bind: 0.0.0.0:40001
    targets: []
  aaaa:
    bind: ewafawef
    targets: []
  abc1:
    bind: 0.0.0.0:4002
    targets: []
options:
  health_check_timeout_ms: 4000
  log_config_file: log4rs.yaml
  max_idle_time_ms: 1000000
dns:
  other: good
  aaaa: basdf
  what???: 192.168.44.101:443
admin_server:
  bind_address: 0.0.0.0
  bind_port: 48888
  username: admin
  password: pass1234
  tls_cert: null
  tls_key: null
  tls_ca_cert: null
  mutual_tls: null
  tls: false
  rocket_log_level: critical
