listeners:
  SSHBTC:
    bind: 0.0.0.0:10022
    targets:
    - 10.88.97.132:22
options:
  health_check_timeout_ms: 4000
  log_config_file: log4rs.yaml
  max_idle_time_ms: 1000000
dns:
  aaaa: basdf
  what???: 192.168.44.101:443
  other: good
admin_server:
  bind_address: 0.0.0.0
  bind_port: 48888
  username: admin
  password: pass1234
  tls_cert: null
  tls_key: null
  tls_ca_cert: null
  mutual_tls: null
  tls: false
  rocket_log_level: critical
